### ISSUE TITLE
Setting ensure to absent is not idempotent 

### ISSUE THREAD

**Issue by erikanderson** [fiddyspence/puppet-sysctl#29]
We have had `tcp_mem` set in our environment for a while now. We recently set the ensure on that value to `absent`. The module removed the value from `/etc/sysctl.conf` but it reports is as removed every run:

```
Notice: /Stage[main]/Profile::Sysctl/Sysctl[net.ipv4.tcp_mem]/ensure: removed
```

This is how it is currently set: 

```
        'net.ipv4.tcp_mem':
          ensure    => 'absent',
          permanent => 'yes',
          value     => '50576 64768 98152';
```

**Comment by fiddyspence** [comment]
You could always just set permanent => 'no', leave the ensure attribute out and that'll remove it from sysctl.conf - do you still care about the values it's set to?
