### ISSUE TITLE
Setting path for alternate config loops when permanent option is set to yes

### ISSUE THREAD

**Issue by rvdlinden** [fiddyspence/puppet-sysctl#32]
In the below example, the file /etc/sysctl.d/90-oracle.conf gets the kernel.shmmax settings added during every run. 

Sysctl {
  path => '/etc/sysctl.d/90-oracle.conf',
}

sysctl { 'kernel.shmmax':
  ensure => 'present',
  permanent => 'yes',
  value => 779538432,
}

Result in /etc/sysctl.d/90-oracle.conf
kernel.shmmax = 779538432
kernel.shmmax = 779538432
kernel.shmmax = 779538432

**Comment by ybrock** [comment]
Noticed the same behavior. At each run of puppet agent, the file pointed by the "path" parameter gets appended with the same value over and over.
