### ISSUE TITLE
Struggling to configure this for different profiles 

### ISSUE THREAD

**Issue by harisiri74** [fiddyspence/puppet-sysctl#33]
Has anyone tried to use this module with different kernel settings for different applications. I use profiles to separate different app nodes and like to configure .pp file specific to that node.
Please help !

**Comment by fiddyspence** [comment]
You mean like using hiera to supply different values depending on e.g. fact values?

**Comment by harisiri74** [comment]
That was quick response, thanks Spence. here is my code: 

# pwd

/etc/puppetlabs/puppet/environments/development/modules/sysctl

 cat manifests/init.pp

# Class: sysctl

#

# This class is a stub for a module that provides a sysctl type and

# 2 providers:

# linux.rb

# darwin.rb

#

# Parameters:

# N/A

#

# Requires:

#

# Sample Usage:

#
class sysctl {
  # foooooooooooo
  # Hari - code goes into hostautomation sysctl directory
  node "malpmtest.mava.micron.com" inherits {
        # puppet resource sysctl net.ipv4.ip_local_port_range permanent=no value="32768"$'\t'"61000"
        #notice: /Sysctl[net.ipv4.ip_local_port_range]/value: value changed '32768 61001' to '32768 61000'
        sysctl { 'net.ipv4.ip_local_port_range':
                ensure    => 'present',
                permanent => 'yes',
                value     => '32768 61001',
                provider  => 'linux'
        }
  }
}

**Comment by fiddyspence** [comment]
I think you probably need to go and learn some more puppet - it doesn't sound like you have a specific issue with this module - maybe start here: https://learn.puppet.com/

**Comment by harisiri74** [comment]
1. How do i tell this code only run on a specific node ? 
2. How do i scale different settings for different nodes ?
